language: rust
rust:
- stable
- nightly
os:
- linux
- osx
- windows
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
after_success:
- |
  # Only build&publish for nightly, on master, for tagged releases.
  if [ "$TRAVIS_BRANCH" == "master" ] &&
          #[ ! -z "$TRAVIS_TAG" ] &&
          [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
          [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      # Set up Windows
      if [ "$TRAVIS_OS_NAME" = "windows" ]; then
          choco install python3
          export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
          pip install maturin
      else
          # Linux and OSX
          export PATH=$PATH:$(python -m site --user-base)/bin
          pip install --user maturin
      fi
      # Get maturin and publish module.
      maturin publish -u "__token__" --cargo-extra-args="--features python-module"
  fi
env:
  global:
  - secure: FVHfVYPLQvtuj2VExoY969RGrfWP0xawt0IPlO4rrkpnfSEBsJrMJjIQ905RbeSOdmdfzTs+l9CyfELmh1NFIC/aCcDU1aIdYsHUcT0m+3j1ldnwquM3rfbpeY1VDNDnZvDZqq7ticir9smxa4B3TkY3/6JRWm0bNe1uWSWB4KJRUye+cyd6UHVJz4dS3GuVIpYfKOG/Sqqv2uJe5SRt+5k8j3tGbDA7AVN71UL0lNh8NNeZc8FIuOe7E0YTiqbSdsNN/1CvzcvOUX70CutLM4vg3OAW1XAilTJcDChbOkR+P/b+THyBNgELHP7rEe5K1e8ofELn65l9A37ZDqqQB6q1sDG8vrbkaFtFwdBpoKVoKBUqhH6OKX/fgJD2MQlPiFvnF1wlteiYPBNKeoI3q+53xKkbQe1d+jvJQYhMbwvj3uBrCMz/ncRIImP7xkKwBmJJz+Tu7sLuH8S9CBmHes8hjq1Q/oaqn3+dyZO/ewWcS0zUeU5QacLe28S4gseFEcsZYUK28t8eelFwgS7+nSejLeyZIGN9ahrz85eurlrNnJA7VNojafY5iqiVj+nADGOgR07lBjl+4a8BTXMwPUTPhTAwaIjrQ5n5sqvoR0kct/xgMnf0apT9XkcY3aa+OS7q4CEr1yfy2pcr17PK6BWwrLsu1Gx7f6DNdc91fm8=
