name: build-python

on:
  push:
    branches: [ fix-build ]
  pull_request:
    branches: [ fix-build ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: "Build python module via maturin"
        run: |
          pip3 install --user maturin
          $(python3 -m site --user-base)/bin/maturin build --cargo-extra-args="--features python-module"
